In [1]:
import numpy as np

# DataType and Attrbutes

In [53]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[1,2.0,3.2],[1,2.0,3.2]])
a2

array([[1. , 2. , 3.2],
       [1. , 2. , 3.2]])

In [9]:
a3=np.array([[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[2,3,4],[4,5,6]]])
a3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [10]:
a1.shape,a2.shape,a3.shape

((3,), (2, 3), (2, 3, 3))

In [11]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [13]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [15]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [17]:
import pandas as pd

In [20]:
df=pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.2
1  1.0  2.0  3.2

## Arrays

In [21]:
sample_array=np.array([1,3,4])
sample_array

array([1, 3, 4])

In [22]:
one=np.ones((2,3))#shift + tab
print(one)

[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
one.dtype

dtype('float64')

In [27]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [30]:
r_array=np.random.randint(0,10,size=(2,3))
r_array

array([[1, 6, 2],
       [0, 9, 0]])

In [31]:
r=np.random.random((2,3))
r

array([[0.89854263, 0.51333796, 0.77832964],
       [0.80558327, 0.84717249, 0.15393463]])

In [37]:
#psudo random numbers
np.random.seed(seed=2)
r_a=np.random.random((5,4))
r_a

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548]])

## viewing arrays and matrices

In [38]:
np.unique(r_a)

array([0.02592623, 0.07964548, 0.13457995, 0.18443987, 0.20464863,
       0.26682728, 0.29965467, 0.33033482, 0.4203678 , 0.43532239,
       0.4359949 , 0.49423684, 0.51357812, 0.52914209, 0.54966248,
       0.61927097, 0.62113383, 0.78533515, 0.84656149, 0.85397529])

In [39]:
a2[0]

array([1. , 2. , 3.2])

In [40]:
a3

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [42]:
a3[:2,:2,:2]

array([[[1, 2],
        [1, 2]],

       [[1, 2],
        [2, 3]]])

In [44]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[4, 6, 3, 9, 2],
         [0, 4, 2, 4, 1],
         [7, 8, 2, 9, 8],
         [7, 1, 6, 8, 5]],

        [[9, 9, 9, 3, 0],
         [0, 2, 8, 8, 2],
         [9, 6, 5, 6, 6],
         [6, 3, 8, 2, 1]],

        [[4, 8, 1, 6, 9],
         [5, 1, 2, 4, 7],
         [6, 4, 5, 8, 3],
         [0, 0, 5, 7, 5]]],


       [[[0, 8, 6, 5, 1],
         [7, 4, 3, 6, 1],
         [4, 0, 8, 5, 4],
         [2, 9, 7, 1, 9]],

        [[2, 1, 0, 7, 1],
         [8, 9, 0, 7, 0],
         [5, 2, 5, 1, 3],
         [3, 1, 8, 6, 8]],

        [[1, 5, 7, 0, 9],
         [1, 5, 9, 2, 0],
         [0, 4, 6, 3, 1],
         [8, 5, 9, 5, 4]]]])

In [45]:
a4[:,:,:,:3]

array([[[[4, 6, 3],
         [0, 4, 2],
         [7, 8, 2],
         [7, 1, 6]],

        [[9, 9, 9],
         [0, 2, 8],
         [9, 6, 5],
         [6, 3, 8]],

        [[4, 8, 1],
         [5, 1, 2],
         [6, 4, 5],
         [0, 0, 5]]],


       [[[0, 8, 6],
         [7, 4, 3],
         [4, 0, 8],
         [2, 9, 7]],

        [[2, 1, 0],
         [8, 9, 0],
         [5, 2, 5],
         [3, 1, 8]],

        [[1, 5, 7],
         [1, 5, 9],
         [0, 4, 6],
         [8, 5, 9]]]])

## Manipultaing arrays

# Arithmetic 

In [54]:
a1

array([1, 2, 3])

In [49]:
one=np.ones(3)
one

array([1., 1., 1.])

In [55]:
a1+one

array([2., 3., 4.])

In [56]:
a2

array([[1. , 2. , 3.2],
       [1. , 2. , 3.2]])

In [57]:
a1*a2

array([[1. , 4. , 9.6],
       [1. , 4. , 9.6]])